version: '3.8'
services:
  php83-swoole51x-openssl:
    build: .
    container_name: php83-swoole51x-openssl
    image: tning6666/php83-swoole51x-openssl
    tty: true
    volumes:
      - .:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: php83
